### PR TITLE
Pass fixture instance into example listeners

### LINKED ISSUE #246: `@AfterExample` triggered for wrong example
When using the `@AfterExample` annotation, the initial instance of the fixture is used, rather than the instance relating to the specific example. This is visible with the `per_example_parallel` branch of concordion-scope-examples.

The cause appears to be since the listener is created once for all examples in ConcordionBuilder:

```
        FixtureExampleHook fixtureExampleHook = new FixtureExampleHook(fixture);
        withOuterExampleListener(fixtureExampleHook);
        withExampleListener(fixtureExampleHook);
```

### PR DESCRIPTION
**Pull request by nigelcharman**
Please don't merge this PR yet while we look at the impact on existing extensions.

This will impact at least the ScreenshotExtension (which implements `Command`) and the ParallelRunExtension (which has an outer example listener).

To ensure that the correct fixture instance is utilised in methods annotated with `@BeforeExample` and `@AfterExample`,  pass the Fixture object into `ExampleEvent`s, which necessitates passing it through `ExampleCommand`s.

Fixes #246 and #262.

### CODE REVIEW

File: src/main/java/org/concordion/Concordion.java [hunk 1]
```diff
@@ -78,7 +78,7 @@ public void override(Resource resource) throws IOException {
     public ResultSummary process(Fixture fixture) throws IOException {
         SummarizingResultRecorder resultRecorder = new SummarizingResultRecorder();
         resultRecorder.setSpecificationDescription(fixture.getSpecificationDescription());
-        getSpecification(fixture).process(evaluatorFactory.createEvaluator(fixture.getFixtureObject()), resultRecorder);
+        getSpecification(fixture).process(evaluatorFactory.createEvaluator(fixture.getFixtureObject()), resultRecorder, fixture);
```
Comment (crstim) [inline src/main/java/org/concordion/Concordion.java]: It seems odd having to pass the fixture to two calls here on the same line.

File: src/main/java/org/concordion/api/AbstractCommandDecorator.java [hunk 2]
```diff
@@ -11,26 +11,26 @@ public AbstractCommandDecorator(Command command) {
         this.command = command;
     }
 
-    public void setUp(final CommandCall commandCall, final Evaluator evaluator, final ResultRecorder resultRecorder) {
+    public void setUp(final CommandCall commandCall, final Evaluator evaluator, final ResultRecorder resultRecorder, final Fixture fixture) {
         process(commandCall, evaluator, resultRecorder, new Runnable() {
             public void run() {
```
Comment (crstim) [inline src/main/java/org/concordion/api/AbstractCommandDecorator.java]: Have we moved to the version of Java that has Lambdas yet? If so, the whole 'new Runnable' thing isn't needed anymore.

File: src/main/java/org/concordion/Concordion.java (hunk 1 above)
Comment (nigelcharman) [reply src/main/java/org/concordion/Concordion.java]: Good spot, SpecificationByExample holds the fixture, so I'll remove it from the `process` method.

**Comment by crstim** [comment]
The PR looks OK. However, 3/4ths of it (or more) is just adding a new parameter to lots of existing methods. This is a code smell to me - and indicates we have need of a Data object of some type to encapsulate all the arguments - and mostly they are "CommandCell, Evaluator, ResultRecorder, and Fixture". This indicates some sort of "RuntimeContext" argument. It might be sensible to do this refactor now because we're breaking the API anyway - then we can add new things to the RuntimeContext object later and not break the API as badly.

(RuntimeContext is a bad name - but it's a starting point)

File: src/main/java/org/concordion/api/AbstractCommandDecorator.java (hunk 2 above)
Comment (nigelcharman) [reply src/main/java/org/concordion/api/AbstractCommandDecorator.java]: Not yet, still supporting JDK 7 currently (and checking with openjdk7 on Travis). Moving up can't be far away though.

File: src/main/java/org/concordion/Concordion.java (hunk 1 above)
Comment (nigelcharman) [reply src/main/java/org/concordion/Concordion.java]: I've modified the handling so `getSpecification()` no longer requires a fixture
